'use client';
import { Logo, LogoText } from '@/components/Logo/Logo';
import './globals.css';
import { Inter } from 'next/font/google';
import { Box } from '@/components/Box/Box';

const inter = Inter({ subsets: ['latin'] });

import { ConfigProvider, Layout } from 'antd';
import { NavBar } from '@/components/NavBar/NavBar';

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Layout style={{ minWidth: 290, width: '100%' }}>
          <Box
            display="flex"
            position="relative"
            alignItems="center"
            justifyContent="space-around"
            padding="0 20px"
            minHeight={80}
          >
            <Logo />
            <LogoText />
          </Box>
          <NavBar />
        </Layout>

        <>{children}</>
      </body>
    </html>
  );
}
