'use client';
import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

import { Layout } from 'antd';
import { Header } from '@/components/Header/Header';
import { CartWrapper } from '@/context/state';

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <CartWrapper>
        <body className={inter.className}>
          <Layout style={{ minWidth: 290, width: '100%' }}>
            <Header />
            {children}
          </Layout>
        </body>
      </CartWrapper>
    </html>
  );
}
